<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.659" timestamp="2023-10-01T08:50:09.347473" hostname="ubuntu-Latitude-5490"><testcase classname="" name="server.testing.app_test" time="0.000"><error message="collection failure">ImportError while importing test module '/home/ubuntu/Development/code/phase-4/python-p4-authorization-lab/server/testing/app_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
server/testing/app_test.py:3: in &lt;module&gt;
    from app import app
server/app.py:7: in &lt;module&gt;
    from models import db, Article, User
server/models.py:1: in &lt;module&gt;
    from flask_sqlalchemy import SQLAlchemy
../../../../.local/share/virtualenvs/python-p4-authorization-lab-NEZgLjep/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py:14: in &lt;module&gt;
    from flask import _app_ctx_stack, abort, current_app, request
E   ImportError: cannot import name '_app_ctx_stack' from 'flask' (/home/ubuntu/.local/share/virtualenvs/python-p4-authorization-lab-NEZgLjep/lib/python3.10/site-packages/flask/__init__.py)</error></testcase></testsuite></testsuites>